import { Anchor } from "@mantine/core";
import { UsersStack } from "components/user-stack";
import Head from "next/head";
import { useRouter } from "next/router";
import Network from "types/network";

interface Props {
  network: Network[];
}
export default function NetworkList({ network }: Props) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Anchor
        onClick={() => {
          router.push("/network/create");
        }}
        target="_blank"
      >
        Create
      </Anchor>
      <UsersStack data={network} />
    </>
  );
}
export async function getStaticProps() {
  const res = await fetch("http://localhost:8080/network");

  const network = await res.json();

  return {
    props: {
      network,
    },
  };
}
