import Head from "next/head";
import React, { useEffect, useState } from "react";
import { Anchor, Button, Grid, Space, TextInput } from "@mantine/core";
import { useRouter } from "next/router";
import Network from "types/network";
import NetworkForm from "components/network-form";
import { INITIAL_NETWORK } from "app/constant";

export default function NetworkList() {
  const router = useRouter();
  const [data, setData] = useState<Network>(INITIAL_NETWORK);

  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NetworkForm method="CREATE" />
    </>
  );
}
