import Head from "next/head";
import React from "react";
import Network from "types/network";
import FamilyForm from "components/family-form";
import Family from "types/family";
import { useRouter } from "next/router";
import useSWR from "swr";
import { fetcher } from "lib/utils";

interface Props {
  family: Family;
}

export default function FamilyMemberUpdate() {
  const router = useRouter();
  const id = router.query.id as string;
  const { data, error } = useSWR(`/api/family/${id}`, fetcher);
  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;
  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FamilyForm family={data} method="PUT" />
    </>
  );
}
