import Head from "next/head";
import Family from "types/family";
import FamilyList from "components/family-list";
import useSWR from "swr";
import { fetcher } from "lib/utils";

interface Props {
  family: Family[];
}

export default function FamilyHome() {
  const { data, error } = useSWR("/api/family", fetcher);
  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;
  return (
    <>
      <Head>
        <title>Family | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FamilyList family={data} />
    </>
  );
}
