import Head from "next/head";
import React from "react";
import FamilyForm from "components/family-form";
import { INITIAL_FAMILY } from "app/constant";

export default function FamilyMemberCreate() {
  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FamilyForm method="POST" data={INITIAL_FAMILY} />
    </>
  );
}
