import Head from "next/head";
import { INITIAL_FAMILY } from "lib/constant";
import React, { useState } from "react";
import Family from "types/family";
import FamilyForm from "components/family-form";

export default function FamilyMemberCreate() {
  const [form, setForm] = useState<Family>(INITIAL_FAMILY);
  const handleChange = (e: any) => {
    const { value, name, type, checked } = e.target;

    setForm((state) => ({
      ...state,
      [name]: type === "checkbox" ? checked : value,
    }));

    console.log(form);
  };
  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FamilyForm family={INITIAL_FAMILY} method="POST" />
    </>
  );
}
