import { Autocomplete, Button, Skeleton, Space } from "@mantine/core";
import Head from "next/head";
import { useRouter } from "next/router";

export default function UserInfo() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>User Information | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Autocomplete
        label="Contact, Relation, People"
        placeholder="Pick one"
        data={["React", "Angular", "Svelte", "Vue"]}
      />
      <Space h="md" />
      <Skeleton height={50} circle mb="xl" />
      <Skeleton height={8} radius="xl" />
      <Skeleton height={8} mt={6} radius="xl" />
      <Skeleton height={8} mt={6} width="70%" radius="xl" />
      <Space h="md" />
      <Button
        onClick={() => {
          router.push("/userinfo/create");
        }}
      >
        Add network
      </Button>
    </>
  );
}
