import Head from "next/head";
import { useEffect } from "react";
import { UserInfoIcons } from "components/user-info-icons";
import { useAppDispatch } from "app/hooks";
import { useRouter } from "next/router";
import { dispatchNetwork } from "app/utils";
import { Anchor } from "@mantine/core";

export default function FamilyMember() {
  const router = useRouter();
  const dispatch = useAppDispatch();

  useEffect(() => {
    if (router.isReady) {
      const { id } = router.query;
      fetch(`/api/network/${id}`)
        .then((res) => res.json())
        .then((data) => {
          dispatchNetwork(dispatch, data);
        });
    }
  }, [router.isReady]);

  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Anchor
        onClick={() => {
          router.push("/network");
        }}
        target="_blank"
      >
        Back
      </Anchor>
      <UserInfoIcons />
    </>
  );
}
