import FamilyList from "components/family-list";
import Head from "next/head";
import Family from "types/family";

interface Props {
  family: Family[];
}

export default function FamilyHome({ family }: Props) {
  return (
    <>
      <Head>
        <title>Family | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl p-4">亲属</div>
      <FamilyList family={family} />
    </>
  );
}
export async function getStaticProps() {
  const res = await fetch("http://localhost:8080/family");

  const family = await res.json();

  return {
    props: {
      family,
    },
  };
}
