import Head from "next/head";
import React, { useState } from "react";
import { useRouter } from "next/router";
import Family from "types/family";
import NetworkForm from "components/network-form";
import { INITIAL_NETWORK } from "app/constant";

export default function FamilyMemberCreate() {
  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NetworkForm method="CREATE" />
    </>
  );
}
