import Head from "next/head";
import Network from "types/network";
import NetworkList from "components/network-list";
import useSWR from "swr";
import { fetcher } from "lib/utils";

interface Props {
  network: Network[];
}

export default function NetworkHome() {
  const { data, error } = useSWR("/api/network", fetcher);
  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;
  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl p-4">人际</div>
      <NetworkList network={data} />
    </>
  );
}
