import Head from "next/head";
import { useRouter } from "next/router";
import Network from "types/network";
import NetworkList from "components/network-list";

interface Props {
  network: Network[];
}
export default function NetworkHome({ network }: Props) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl p-4">人际</div>
      <NetworkList network={network} />
    </>
  );
}
export async function getStaticProps() {
  const res = await fetch("http://localhost:8080/network");

  const network = await res.json();

  return {
    props: {
      network,
    },
  };
}
