import Head from "next/head";
import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Network from "types/network";
import { INITIAL_NETWORK } from "app/constant";

export default function NetworkList() {
  const router = useRouter();
  const [data, setData] = useState<Network>(INITIAL_NETWORK);

  useEffect(() => {
    if (router.isReady) {
      const { id } = router.query;
      fetch(`/api/network/${id}`)
        .then((res) => res.json())
        .then((data) => {
          setData(data);
        });
    }
  }, [router.isReady]);

  const handleChange = (e: any) => {
    const { value, name, type, checked } = e.target;
    setData((state) => ({
      ...state,
      [name]: type === "checkbox" ? checked : value,
    }));
  };
  console.log(data);

  return (
    <>
      <Head>
        <title>Network | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <NetworkForm method="PUT" data={data} /> */}
      <input
        name="address"
        onChange={handleChange}
        value={data.address === null ? "" : data.address}
        className="bg-zinc-800 mt-1 block w-full rounded-md border p-2 border-zinc-500 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
      />
    </>
  );
}
