import Head from "next/head";
import { useRouter } from "next/router";

export default function UserInfo() {
  return (
    <>
      <Head>
        <title>User Information | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}
