import Head from "next/head";
import { useRouter } from "next/router";

export default function UserInfo() {
  return (
    <>
      <Head>
        <title>User Information | Relationship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input className="bg-zinc-800 mt-1 block w-full rounded-md border p-2 border-zinc-500 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" />
    </>
  );
}
